test: true
RMTpass: "LinuxRulesDonald" #Remote access passwor
#Permission plugin group ; permission you want to use
taxes: 6.5 #Percentage tax to execute
DefaultRank: "Citizen" #What rank do you want everyone to have