name: SmartStaff
author: FluxedScript
description: Get a custom head!
version: 1.1
main: tk.ifutureserver.fluxedscript.smartstaff.Main
depend: [Vault]
commands:
  bbtest:
    description: Test the plugin
    usage: /bbtest
  staffmode:
    description: Staff mode
    usage: /staffmode
    permission: ss.use
    aliases: [staff,sm,rpmode]
  playtime:
    description: Player time
    usage: /playtime
    aliases: [pt]
  taxall:
    description: Tax all players
    usage: /taxall
    aliases: [taxday,collecttaxes]